### ISSUE TITLE
Request : k8s CronJob

### ISSUE THREAD

**Issue by raphaelauv** [portainer/portainer-k8s#5]
Hey , a big thanks for all your work !!

We really appreciate the portainer beta , but it do not support native CronJob https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/

Could be a very nice feature :)

**Comment by deviantony** [comment]
Hi @raphaelauv 

Thanks for the feedback ! We have a repository that was specifically designed for the feedback about the BETA version, I've closed your issue and referenced it here: https://github.com/portainer/kubernetes-beta/issues/19
