### ISSUE TITLE
no arm64

### ISSUE THREAD

**Issue by outbackdingo** [portainer/portainer-k8s#6]
Ive got k8s running on a Yocto build for the nvidia nano .. its arm64 ...

Linux jetson-nano-qspi-sd 4.9.140-l4t-r32.3.1+g47e7e1cb0b49 #1 SMP PREEMPT Sun Jan 19 12:07:53 UTC 2020 aarch64 GNU/Linux

anyway we can get a aarch64 build ?

**Comment by deviantony** [comment]
Hi @outbackdingo 

Yes, it will be possible to deploy it on arm64 as soon as it is out of beta (by the end of June).

Closing this issue and referencing it in our beta feedback repository via https://github.com/portainer/kubernetes-beta/issues/7
