### ISSUE TITLE
cannot read property 'port' of undefined

### ISSUE THREAD

**Issue by geek-baba** [portainer/portainer-k8s#7]
Used the default loadbalancer install and getting the error when accessing dashboard, application etc

```
curl -LO https://raw.githubusercontent.com/portainer/portainer-k8s/master/portainer.yaml
kubectl apply -f portainer.yaml
```
<img width="352" alt="Screen Shot 2020-06-17 at 8 36 32 AM" src="https://user-images.githubusercontent.com/3969460/84898744-ba363b80-b075-11ea-8c6e-b96825bdace1.png">

**Comment by deviantony** [comment]
This is a known issue and was reported via https://github.com/portainer/kubernetes-beta/issues/1#issuecomment-642253819

Closing the issue, I'll post an updated image in the kubernetes-beta repository related issue.
